import math
print(3 + 4)
print(3 - 4)
print(3 * 4)
print(3 % 4)
print(3 / 4)
print(3 ** 4)
print(3 // 4)
print('Tuan')
print('Nguyen')
print('Viet Nam')
print('I am enjoying 30 days of Python')
print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type('Tuan'))
print(type('Nguyen'))
print(type('Viet Nam'))
print(type(True))
print(type(False))
print(type((1,2,3)))
print(type({1,2,3}))
print(type({
    'a': 1,
    'b': 2,
    'c': 3
}))
# Exercise: Level 3 - Euclidean distance between (2,3) and (10,8)
point_a = (2, 3)
point_b = (10, 8)
distance = math.sqrt((point_b[0] - point_a[0]) ** 2 + (point_b[1] - point_a[1]) ** 2)
print('Euclidean distance between', point_a, 'and', point_b, 'is', distance)
